Refactored ROV Control
Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming pull request #11
Opened 2022-10-20 01:08 UTC by Hermanoid

Good Stuff?

2022-11-10 02:55 UTC, yameatmeyourdead requested changes
Refactor garbage variables to dictionaries. Otherwise LGTM

2022-11-10 02:55 UTC, yameatmeyourdead commented on src/rov/rov_control/rov_control/JoySubscriber.py
> +        self.hat_right = False
Make this a dict

2022-11-10 02:55 UTC, yameatmeyourdead commented on src/rov/rov_control/rov_control/JoySubscriber.py
> +        self.hat_y = self.apply_deadzone(msg.axes[mapping["hat_y"]], deadzone)
Make this a dict

2022-11-10 02:55 UTC, yameatmeyourdead commented on src/rov/rov_control/rov_control/JoySubscriber.py
> +        for button in dir(self.toggled_buttons):
change this function to loop over the previously created dict

2022-11-17 02:28 UTC, Hermanoid reviewed
APPROVE IT

2022-11-17 02:28 UTC, yameatmeyourdead approved these changes

2022-11-17 02:29 UTC, merged