Refactor Flight Control
Colorado-School-of-Mines-Robotics-Club/MATE_ROV_Programming pull request #18
Opened 2023-03-02 02:37 UTC by yameatmeyourdead

2023-03-09 02:09 UTC, Hermanoid requested changes
Remove old dumb code. Otherwise good.

2023-03-09 02:09 UTC, Hermanoid commented on src/rov/flight_controller/include/flight_controller/Thruster.hpp
> +inline static float throttle_from_thrust(const float thrust, bool clamping = true) {
Remove this stuff?

2023-03-09 02:09 UTC, Hermanoid commented on src/rov/flight_controller/include/flight_controller/flight_controller.hpp
> +    rclcpp::Publisher<rov_interfaces::msg::PWM>::SharedPtr _publisher;
Publisher of what? Name your duds! Professor Baldwin just released V20 of the coding standards document and you're going to be docked points!!

2023-05-06 03:58 UTC, yameatmeyourdead commented
Changes implemented, fixes applied, physical tests run. As there are 53 commits in this PR im going to squash and merge to not continue to pollute our already over polluted git tree

2023-05-06 04:01 UTC, merged